### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Jiahao-Ma** [rakhimovv/npbgpp#12]
Hi authors,

This is such an awesome works! I would like to follow your work. Currently, I suffer from some problems. When I jump into your dataset, I found there are only point cloud files that are provided in the dataset folder. Could you please provide me with the complete dataset similar to the data in example folder? I really appreciate it for your assistance. 

Cheers,
Jiahao

**Comment by rakhimovv** [comment]
Hello @Jiahao-Ma ! Thanks for your interest.

All the datasets are distributed under various licenses and freely available for academic use. Check the corresponding datasets' github pages/websites.
We provided the example scenes just to ease the process of setting the data environment.

The only additional data is point clouds which we added

**Comment by Jiahao-Ma** [comment]
Thanks for your reply! @rakhimovv 
As you know, you provide the mask for image in example folder, while point cloud folder doesn't contain the mask. If I tend to train the pipeline from scratch or evaluate the rest of data, I need to make the mask by myself. Or can you tell me how you get the mask of the object based on this sparse point cloud (in the DTU dataset), is it by segmentation?

**Comment by TArdelean** [comment]
Hello @Jiahao-Ma,

We use publicly available datasets. We provide the point clouds because they are not part of the original datasets; however, to obtain the images, camera poses, and masks you should download them from the corresponding location (provided by the datasets' authors).
In the case of DTU, we use the set of masked scenes. You can find how to download this data here: https://github.com/lioryariv/idr

**Comment by Jiahao-Ma** [comment]
I really appreciate it!
